### ISSUE TITLE
Sakana

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#1]
- [ ] 1.~~同一个客人不管点了多少到菜都希望打在同一张的铁板图纸上~~

先前我已经帮他在cashier那边把堂吃勾去掉不知道为什么他打出来时候有变得有收据了,在我去掉勾后我打印了一次已经没有了收据订单了

**Comment by UnitedPOS** [comment]
> 2.希望能锁住铁板桌子订餐时只能点铁板桌子菜单上面的 无法点外卖那边的铁板餐  相同 客人买外卖和正常堂吃桌子下也无法点击到铁板桌子那边的铁板菜单

**Comment by UnitedPOS** [comment]
3.预约功能开启来

**Comment by qqqpos** [comment]
4.hibachi 桌子上面点击地方价格to go这个键

**Comment by qqqpos** [comment]
5.堂吃定（TImer)时加入选项 可以提前时间 延后时间  取消定时间

**Comment by qqqpos** [comment]
6.hibachi 桌子上面点餐后 客人在要求加头台或其他不是hibachi的餐是 输入完 Hibachi的打印机不需要在打印一次刚刚打入的菜  只要打印后面的菜项

**Comment by qqqpos** [comment]
7.堂吃桌子和hibachi桌子上面都增加人数座位按键   列如在hibachi桌子上面来了2位客人先  他们先下单后面在来一位朋友 时可以在他们原始单子上面增加 座位  无需在开新的订单后在合并订单

**Comment by qqqpos** [comment]
8.  今晚更新完麻烦你把他的先前玩的order订单还有 刷卡记录都删除掉  不要把员工的Pay roll 记录删除  一定要记得这部分 Pay roll不要删除

**Comment by qqqpos** [comment]
9.上述全部弄好后 帮他更新完麻烦在微信上面给她回复下  谢谢

**Comment by qqqpos** [comment]
Bar桌子转成Hibachi桌子后再编辑的话 不会显示Hibachi桌子的下单方式。
