### ISSUE TITLE
打开允许付款后不打印订单功能后

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#105]
如题，打开允许付款后不打印订单功能与付款后设置所以物品为打印完成功能， 按“打印”按钮厨房打印机仍然会打印出来

**Comment by huangxuewu** [comment]
![a9470f99ffe605ff257797ebeefef25](https://user-images.githubusercontent.com/6463693/49688644-3c3dbf80-fae3-11e8-9f20-d1020921b14d.png)
这个?
