### ISSUE TITLE
Sushi Yasaka Report Request

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#108]
- [x] 希望能分清楚Online Order的Delivery和Pick Up小费 与 Credit Card的Delivery 和Pick Up小费

- [ ] ~~希望能在下午Cashier Out后 晚上再Cashier In的时候能将History里面的单子清空并且使Order #从1开始~~

**Comment by huangxuewu** [comment]
客人已经使用电脑连接刷卡机, 此功能已经不需要
