### ISSUE TITLE
SUSHI YASAKA

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#111]
1.第三方 tip 里面包括2个类型tip（第三方的送餐tip和和店里来取的tip ，因为有时候客人点了第三方的餐但是会给cashier小费，这样不知道应该拿多少小费）
2 做tax free的时候要把tax free 的金额写出来，因为会计师楼做账的时候。会发现总额跟税价格不对

**Comment by huangxuewu** [comment]
已经完成
