### ISSUE TITLE
0.9.96 信用卡付款测试

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#116]
- [x] 使用信用卡付款后再去删除Payment时会出现卡屏现象

- [ ] 当使用同一张卡两次付款同样金额的时候会出现卡屏现象

**Comment by qqqpos** [comment]
- [ ] 在Terminal界面点作废信用卡付款记录时有时会出现卡屏现

**Comment by huangxuewu** [comment]
关于第二需要按住按钮才可以执行

**Comment by qqqpos** [comment]
- [ ] 过账成功后做退款操作时， 终端机会显示成功 但电脑屏幕显示操作失败
