### ISSUE TITLE
新客人要求--铁板日餐店

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#121]
-1 [ ] 铁板日餐店开再旅游区比较多的都是party--他们的餐都有跟着汤或沙拉 的 这些配菜不需要再厨房或sushi打印机打印。。。现在问题是比如来了20位客人 其中5人和汤15人吃沙拉 时老板希望是再电脑上面直接显示出来总共多少份汤和多少沙拉 。。。不需要启台小姐再去点算数量来拿汤和沙拉。。能够快速显示再点餐页面显示出来

**Comment by huangxuewu** [comment]
已经完成
