### ISSUE TITLE
急急急急急急     wok Express 

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#137]
- [ ] ~~1.客人要求说希望菜组和菜名有不同颜色区分开~~

- [x] 2.
![_20190120143329](https://user-images.githubusercontent.com/28742304/51444054-67a9f180-1cc0-11e9-9d1c-0e488e4a8b4f.jpg)再菜品下方增加快速添加物品如图

**Comment by huangxuewu** [comment]
多个颜色会导致界面杂乱, 此功能不打算实现
