### ISSUE TITLE
Little Tokyo需要更新

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#148]
Little Tokyo需要更新到History界面
![image](https://user-images.githubusercontent.com/28742304/52535660-25079200-2d1f-11e9-83dc-46267304f909.png) 有打折快捷键的版本

注：同时有两部ipad，分别在S1电脑和S2电脑。

**Comment by huangxuewu** [comment]
安排今天晚上

**Comment by huangxuewu** [comment]
已更新 需要设置刷卡机
