### ISSUE TITLE
Little Tokyo-关于Service Fee问题

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#157]
- [ ] 1. 客人想把原来收据打印出来的Service Fee这个单词改成多少% gratutiy显示在收据上
![_20190218135926](https://user-images.githubusercontent.com/28742304/52971463-92519d80-3385-11e9-93c0-1bd4003e2ecb.jpg)

**Comment by huangxuewu** [comment]
![ef2ebedb8141dbe7a2469cacb4088e4](https://user-images.githubusercontent.com/6463693/53046023-1165d500-345d-11e9-8b5c-ad656c6d68e9.png)

**Comment by huangxuewu** [comment]
在堂吃设定里面自动服务费的别名中 加入 百分比符号 即可
