### ISSUE TITLE
点单添加菜项时候无法单独进行操作

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#17]
点单时候 如果有两道菜一样的 但其中一道菜是有要求的， 无法进行单独操作。
第一道菜芥兰鸡设置完要求少芥兰后， 再点一道芥蓝鸡， 第一道和第二道菜会拼在一起， 变成两道芥蓝鸡少芥兰

**Comment by huangxuewu** [comment]
0.8.86 版本将新增一个判断 只有在没有SIDE OPTION 和CHOICESET 的情况之下才会叠加
