### ISSUE TITLE
0.99.98 发现coupon有问题。

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#175]
![image](https://user-images.githubusercontent.com/28742304/55642179-c77f4700-579d-11e9-94d8-a2d35f2a68ce.png)
![image](https://user-images.githubusercontent.com/28742304/55642213-dbc34400-579d-11e9-9e99-12e344bd827e.png)

如题，发现该版本coupon难以开启。需要在应用coupon界面反复开关开关操作才能达到应用coupon的目的。 并且折扣金额出现错误。 应该折扣额为5元，但实际折扣额为10元。

**Comment by huangxuewu** [comment]
该版本COUPON 尚未完成界面设计

**Comment by huangxuewu** [comment]
已经完成设计 2019-05-01 之后的版本都可以使用.
