### ISSUE TITLE
主页面OPEN Cash Drawer 修改

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#195]
- [x] 1. Open Cash Drawer时---使用需要密码才能打开方式下-在这种状态下企台想开钱箱需要使用经理级别以上的人来帮她开启钱箱  ---而非现在只要用自己的密码就能打开

**Comment by huangxuewu** [comment]
![1512df7c44a116d1bc7ff8c7f2f97f0](https://user-images.githubusercontent.com/6463693/57173223-814bf080-6dfa-11e9-84fe-cc5ba12f8741.png)
