### ISSUE TITLE
假发店item出现问题今晚处理

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#208]
- [ ] 1.前台小姐说更新后使用添加物品时后台加好后去前台扫。。无法扫出

- [ ] 2.现在前台小姐从新又把有问题的3个category从新发一份Excel来要我们帮它从新导入进去

- [ ] 3. 和前台小姐说了让他今晚留电脑

- [ ] 4. 新的Excel 应该已经发送到你邮寄里去了

**Comment by huangxuewu** [comment]
要在物品upc里面打入 barcode
