### ISSUE TITLE
分单后加菜再进行二次分单， 出现异常

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#21]
![_20180527172708](https://user-images.githubusercontent.com/28742304/40590778-38ff9842-61d3-11e8-8cee-ae671b5571a8.png)
![_20180527172659](https://user-images.githubusercontent.com/28742304/40590779-390aed1e-61d3-11e8-998f-598e4e7927a7.jpg)

客人先分单后， 又添加了4个 spicy mayo 但是分单界面只显示2个spicy mayo， 后来我去添加了2个spicy mayo，刚开始也不会添加到分单界面里面去 ， 我先点了一个其他的mayo 然后在点2个spicy mayo这样才可以正常添加在分单界面里。

**Comment by huangxuewu** [comment]
没有发现相关问题,无法重现BUG
