### ISSUE TITLE
Hirosaki Steak House-需求--今晚客人准备把全部电脑都换成我们软件  6/9/19

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#228]
- [x] 1. sushi Roll 在周二周三时自动做50% off 

- [x] 2. 企台无法自己做合并订单

- [x] 3.在点酒类品时在还没选着跟着物品时无需把酒品名字显示在右边下单处上

- [x] 4.客人想要再企台身上收取小费的费用给商家报表
![微信图片_20190606181129](https://user-images.githubusercontent.com/28742304/59069882-b4185700-8886-11e9-823c-15738aabc9ba.jpg)

**Comment by huangxuewu** [comment]
已经完成
