### ISSUE TITLE
打印机在列表打印模式下会出现问题

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#23]
如题，当打印机使用列表打印的模式的时候 会出现如下bug：

- [x] 1. 当一个物品的名字太长而分两行打印的时候， 那两行字都会由于列表模式而打印出两个方格
- [ ] 2. 当有许多物品的时候，除了第一次点的物品会显示数量以外， 后续的物品除第一行外不再显示数量
- [ ] 3. 当第一个发送出去的物品与后续添加的物品数量相同时， 列表模式将不会检测到该后续新增物品 从而不会打印

**Comment by huangxuewu** [comment]
已知悉,近期修复

**Comment by huangxuewu** [comment]
已经修复
