### ISSUE TITLE
horosaki

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#239]
加一个开启权限，奇台combi或者swap 桌子的时候，可以询问经理密码。还有就是可以在下单后改客人名字，因为正常来说客人都说先点完餐，我们才问客人名字的

- [ ] 2.50%off 的卷 要是原来的价格输入错误了，再修改完正确的价格后仍然无效再50%off组里面

**Comment by huangxuewu** [comment]
问题已经过期
