### ISSUE TITLE
6/16/19 -Sakana 周日晚上更新

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#242]
- [x] 1.客人想要在历史界面里，再左边的recepit键点击时需要输入密码才能打印收据出来
![微信图片编辑_20190613174153](https://user-images.githubusercontent.com/28742304/59469475-e8e65a00-8e02-11e9-8906-49385b2c8124.jpg)

**Comment by huangxuewu** [comment]
客人电脑关机 改成开门前
