### ISSUE TITLE
在后台菜单组选着打印机打印问题

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#244]
- [x] 1.在menu category 里面的 print 选着好要打印的 打印
![微信图片编辑_20190614123410](https://user-images.githubusercontent.com/28742304/59523989-bb4fee00-8ea0-11e9-9198-7c1b48438376.jpg)
机后点保存无效

**Comment by huangxuewu** [comment]
已经修复 2019-07-19版本  需要更新服务器
