### ISSUE TITLE
玉华楼 

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#25]
1.在送餐那个按地址那个画面，可以在keyboard上面加一个 .(点号） 因为他要记录客人在在多远，难后算送餐费，具体操作在空格旁边有个键盘键，可以换掉
~~2.在改启台多少小费的地方加一个按号码的keyboard~~
~~3.要记的分单以后可以加小费~~
~~4.查找地图的时候可以随意调整地图大小吗？像手机或者电脑里面的google一样~~

**Comment by huangxuewu** [comment]
1.我们有按距离自动增加送餐费功能
2.已加入
3.分单的订单可以输入小费
4.没有调整地图大小的必要.这个不是cashier的职责范围

**Comment by qqqpos** [comment]
1.当一个item有两个同样的sub item的时候， 希望能把sub items分成两行打印
2. 当两个item相同的时候，也希望能把两个item分成两行

**Comment by qqqpos** [comment]
想把sub-item当作main item一样能独立打印出来
