### ISSUE TITLE
sakana-要求在历史界面修改一个功能使用

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#251]
- [ ] 1. 老板想在历史界面里左边数据键加入，查看数据时需要输入经理或老板密码才能查看
![微信图片编辑_20190621131615](https://user-images.githubusercontent.com/28742304/59939779-e8634a00-9426-11e9-9039-62f1c6c4dd56.jpg)

**Comment by huangxuewu** [comment]
已有相同功能
