### ISSUE TITLE
7/1/19 Yamato-WI今晚需要从S1店里里面的database搬到Server电脑上

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#261]
- [x] 1. 今晚帮他安装完我们软件后还需要买一个打印的Key

- [x] 2.并且要从他选着S1电脑上把database放到Sever里面去，

- [x] 3.Server需要安装最新IE浏览器

- [x] 4.客人电脑再做系统更新，更新完需重启电脑，更新完需要把自动更新软件关禁

**Comment by huangxuewu** [comment]
Server 打印机尚未设置，

**Comment by qqqpos** [comment]
打印机已经设置好了。。刷卡机也设置完成了 ，现在就差搬database
