### ISSUE TITLE
7/1/19 Teriyaki Asian Food-问题

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#263]
- [x] 1.老板这2天一直说它电脑常出现这样画面如图下
![微信图片_20190701184808](https://user-images.githubusercontent.com/28742304/60471037-cccf1f00-9c30-11e9-8724-77096cb4b67b.jpg)

- [x] 2.我们怀疑时他店里网络问题，这2天他的网络经常断开我们都无法连接上，客人自己也说有时候厨房打印机无法打印。。（注解：怀疑网络问题导致online order那边无法正常连接成功出现上面的画面）

- [x] 3.已通知今晚留电脑查看

**Comment by huangxuewu** [comment]
某些网络公司提供的2合1的路由器 在断线后会自动重启路由器，重启的时候会导致网络状态切换
