### ISSUE TITLE
Coupon-Category % Discount问题

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#265]
- [x] 1.使用category 百分比 Discount后物品X2 后就无法使用成功另其他物品也跟着打折 如图下
![微信截图_20190705144219](https://user-images.githubusercontent.com/28742304/60740310-30a85f00-9f33-11e9-945b-aea1dacd4155.png)
![微信截图_20190705144248](https://user-images.githubusercontent.com/28742304/60740311-30a85f00-9f33-11e9-87bd-630f364b8e22.png)
其中一张没有x2就正常 一旦物品x2就无法导致全部物品都打折

**Comment by huangxuewu** [comment]
已经修复
