### ISSUE TITLE
0.8.88 kitchen 打印机打印两张ticket问题

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#27]
场景一：
1.在堂吃点餐
2.按延迟
3.用定时功能开始定时
4.在堂吃界面点击发送到厨房打印
5. 定时功能随后也会发送ticket到厨房打印

**Comment by qqqpos** [comment]
场景二：
1.两张桌子，两张单，同时定时后 对两张桌子进行合桌
2.两张定时单会打印出来 
3.合桌后消失的桌子里的订单还能进行打印

**Comment by qqqpos** [comment]
场景三：
1.在外等点餐
2.使用定时功能
3.到历史界面找到刚才下的单子，编辑添加菜项
4.再次使用定时功能
5.新添加的菜项会立即在厨房打印机打印出来 并且打印状态依然是未打印状态（意思是该菜项还可以再次打印）

**Comment by qqqpos** [comment]
场景四：
1.在堂吃界面 已添加到定时任务里的菜单仍可以通过定时功能来添加到定时任务里
 也就是说 未打印的菜可以无限次添到定时任务列表里面

2.外等的定时功能使用定时11分钟后打印并且提前10分钟打印后 按道理会1分钟后打印， 但是1分钟后没有任何菜打印出来

**Comment by qqqpos** [comment]
场景五：
1. 堂吃单子在使用了定时功能后
2. 换桌
3.发送到厨房的单子会仍然打印原来未换桌时候的桌位号

**Comment by huangxuewu** [comment]
已知上述问题,关闭
