### ISSUE TITLE
今晚 Sushi99 old 修复员工工资问题

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#270]
- [x] 1. 员工在7/11-7/12发生有人把他这2天工资付款了 ，麻烦今晚修复下把他这2天付掉的工资恢复起来
员工名字
![微信图片编辑_20190719183848](https://user-images.githubusercontent.com/28742304/61569252-83663880-aa54-11e9-8502-c1142095db31.jpg)

- [x] 2.经理刚刚自己用计算机算了下这位员工的上班时间是有包括这两天付款掉的时间在里面，而工资处就没有包含这个员工这2天付款掉的工资在里面

**Comment by huangxuewu** [comment]
应该是他们在点击打印的时候点到了付款

**Comment by huangxuewu** [comment]
已经修复了
