### ISSUE TITLE
Lee's Dynasty-今晚更新软件 8/4

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#281]
- [ ] 1.客人现在使用版本是0.9.79 版本，目前查找礼物卡时输入卡号后会把所有记录的卡全部调出来，而不是单单这张卡号而已。。

- [ ] 2.这个客人没有信用卡

**Comment by huangxuewu** [comment]
客人关机

**Comment by qqqpos** [comment]
客人不再要求更新了
