### ISSUE TITLE
J&C Seafood 希望修改gratuity部分

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#289]
- [x] 1.客人想要再刷卡纸上面直接打印出收取了客户gratuity后再下方加入而外填写gratuity地方如图显示
![微信图片编辑_20190827154721](https://user-images.githubusercontent.com/28742304/63803182-46f2eb80-c8e2-11e9-9920-e652f1b74d1d.jpg)

**Comment by huangxuewu** [comment]
此功能已经实装 2019-11-11 （1.0.16）
