### ISSUE TITLE
1.0测试版 问题

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#296]
9/25/19

- [ ] 1. 上班时间问题-下班时间修改小于上班时间后，无法再进行2次修改画面，如图显示
![微信图片编辑_20190925130430](https://user-images.githubusercontent.com/28742304/65623092-0c3dab00-df95-11e9-8a26-a75968f86a42.jpg)
- [x] 2. 打印机设置数量不保存
- [x] 3. void键无法使用
- [x] 4. OpenFood 打印机选项看不见，如图显示
![微信图片编辑_20190925142031](https://user-images.githubusercontent.com/28742304/65628574-b91d2580-df9f-11e9-8aa9-37149dad39e0.jpg)
- [x] 5. 磅秤设置无法自动保存
- [x] 6. 无法看见磅秤设置处，如图显示
![微信图片编辑_20190925142327](https://user-images.githubusercontent.com/28742304/65628834-3d6fa880-dfa0-11e9-8d59-00f9e60194f5.jpg)

9/29/19

- [ ] 0. 付款前设置小费后再进行付款动作无法再电脑上面显示找零数字,收据上面也是无法显示出来如图下显示
![微信图片_20190930151826](https://user-images.githubusercontent.com/28742304/65909008-93c05b00-e395-11e9-9638-7acad7a53cb6.png)

- [x] 1. 小费四舍五入问题如下显示 {注解：给与15%小费后出现误差}
![微信图片编辑_20190929155607](https://user-images.githubusercontent.com/28742304/65838502-d3257380-e2d1-11e9-8fd7-81c421f8f896.jpg)

- [ ] 2.后台图表内全部无效

- [ ] 3.礼物卡无法使用输入卡号来查询或激活

- [ ] 4.物品数量对齐开启后要求里旁边价格数字无法使用

- [ ] 5. 服务费转成小费无效

- [x] 6.Pre-Payment 出来的小费建议和信用卡单子出来的小费建议，不一致，如图显示
![微信图片_20190930155358](https://user-images.githubusercontent.com/28742304/65911377-8bb6ea00-e39a-11e9-9374-f161be5407ce.png)

- [ ] 7. 商家做了payout后再后台数据库点击payout查看无效

- [ ] 8.  Void掉的订单后厨不会打印出来订单

- [ ] 9.后台员工设置按住Ctrl进行修改无法一次性进行修改所有启台权限

- [ ] 10. 员工界面进去Schedule处一片空白

- [ ] 11. 一个order 情况下，进行打折无法把税也加入进去进行打折，只能单一，一个item情况下可以把税先去掉，再打折后再X税进去

- [ ] 12. 后台菜单Category里面Restrictions 里点击无效如图显示
![微信图片编辑_20190929165847](https://user-images.githubusercontent.com/28742304/65839368-ac1f6f80-e2da-11e9-9d18-882f8847f719.jpg)

- [ ] 13. 限制物品解除后点击无效

- [ ] 14.Email 报表无法启用

- [ ] 15.pay out功能再后台钱箱处开启签名功能后，去前面做pay Out后点击确定键无效

- [ ] 16.后台online Order 基本都无法开启

- [ ] 17.礼物卡购买时使用第三方付款，无法选着是什么名字来的，例如选着visa ,amex,这些

- [ ] 18.点击分单订单进入里面进行，选着第三方付款后，出来总单颜色不会变成已付款状态

- [ ] 19. 外等设置timer 后点延迟退出再右边会看订单边（NaN年)情况如图显示
![微信图片编辑_20190929172858](https://user-images.githubusercontent.com/28742304/65839792-a461ca00-e2de-11e9-94e5-5c9cc2eca942.jpg)

- [ ] 19a.外等timer设置好后再主页面右边点击打印后，再重启软件发现刚刚设置的timer物品还再主页面旁边无法移除去

- [ ] 20. 修复铁板桌位上面的长按住虚线问题，在铁板桌子上面长按住虚线后，在点餐菜会跑到虚线上面去而不是在虚线下面，如图显示
![64562572-4bc09200-d31b-11e9-8fa1-908443c9d92e](https://user-images.githubusercontent.com/28742304/65839868-821c7c00-e2df-11e9-89da-b7bb95e38cab.jpg)

- [x] 21 .堂吃桌位图左上边名字再订单使用中突然变得空白如图显示
![微信图片编辑_20190929173715](https://user-images.githubusercontent.com/28742304/65839917-f5be8900-e2df-11e9-82f9-743905afc074.jpg)

- [ ] 22.座位设置为72个座位后，添加铁板桌位图会变成奇怪样子如图显示
![微信图片编辑_20190929174155](https://user-images.githubusercontent.com/28742304/65839954-767d8500-e2e0-11e9-8d3b-43a521e2a0b5.jpg)

- [ ] 23.再删除新建的座位图时，会连图旧的一起删除掉

9/30/19

- [x] 1. 外等酒报表里面没有包含税再内
![微信图片编辑_20190930133011](https://user-images.githubusercontent.com/28742304/65901647-9a93a180-e386-11e9-8389-25df058a8eee.jpg)

- [ ] 2.后台付款处选着总是默认打印收据模式后，前台付款时不会再电脑上面显示找零金额数字，而是直接关闭

- [x] 3.历史处原来数据名字现在变成付款能否改成（付款记录/付款明细/扎帐）
![微信图片编辑_20190930153325](https://user-images.githubusercontent.com/28742304/65910021-db47e680-e397-11e9-8d12-35bd1dc6b91a.jpg)

- [ ] 4.堂吃Timer 变的无法使用了

- [x] 5. 酒精报表，先查看了详细内容后再却换去简易查看时发现简易里面的内容和详细的一模一样

- [ ] 6. 如果使用第三方付款里面的store Voucher的话，没法再付款界面里的第三方点击到这个单词
![微信图片编辑_20190930161844](https://user-images.githubusercontent.com/28742304/65913596-3381e700-e39e-11e9-8e5a-1eb27f699c9f.jpg)

- [ ] 7. 付款界面里面，第三方付款里面选着可以根据客人店内常用付款模式进行更改

- [ ] 8.订单Void掉一道菜时打包处，再次打印出来的单子上面也有void这道菜再里面显示出来，而不是重新打印一张全新的没有这道void的菜单子再打包单子上面如图显示 （注解：打包打印机设置没有开要打印Viod菜选项)
![微信图片编辑_20190930174354](https://user-images.githubusercontent.com/28742304/65919305-e86dd100-e3a9-11e9-8912-b9bef5e16902.jpg)

- [ ] 9. 分单后订单直接支付总额后，分单订单里面的单子还是显示未付款状态和还能再里面进行2次付款

- [ ] 10. 堂吃桌位订单下单后，再把订单转成外等后直接点退出后，会导致该订单再桌位图上消失要去历史里才能看到该订单

- [x] 11. 小费建议再给出折扣后不会一同进行改变，还是保留折扣前的小费建议

**Comment by huangxuewu** [comment]
21 是因为没有打中文

**Comment by qqqpos** [comment]
> 21 是因为没有打中文

这个不是没有打中文导致，这个是使用中突然变成这样来的
