### ISSUE TITLE
玉华楼

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#30]
~~1.打印收据(第一打印收据就正常,第二次打印要写reprint receipt,并且可以记录下来打印次数,怕企台拿收据重复使用)~~
2.改单记录(小点可以查找改单记录,这个办法都可以.但是在右边收据上面以下单并且删除的单子要表现在上面.可以让人一看就知道这个菜曾经被删除掉)
3.打包receipt(一些专门请打包的店,相对比较忙,而且有时候单子比较大和比较长,所以,有些可以改的单子,重点是不要的菜可以有一个特殊标志表现出来,不要变没有掉
)

**Comment by huangxuewu** [comment]
功能已经完成
