### ISSUE TITLE
Zen

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#31]
又出现跳单的情况.
D2 order the orange chicken and Mongolian chicken super meal.         The order was put on hold,               D4 send the order in and D2 order when with D4 ticket??????
The 2 sweet and sour chicken (table D3) super meal were repeated on another ticket table D1???????????

**Comment by qqqpos** [comment]
![image](https://user-images.githubusercontent.com/28742304/41170797-eaca012e-6b1b-11e8-9a26-436bc5349a59.png)

**Comment by qqqpos** [comment]
![image](https://user-images.githubusercontent.com/28742304/41170814-fbdf622e-6b1b-11e8-8a03-9579b2a51cb9.png)

**Comment by huangxuewu** [comment]
已经修复
