### ISSUE TITLE
lucky chen -pay out问题今晚修复10/29/19

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#312]
- [x] 1. 老板做了payout但是记录那边不会显示出钱减少问题，
![微信图片_20191029174600](https://user-images.githubusercontent.com/28742304/67811837-08111b80-fa74-11e9-98b2-14fe6e5ef29f.png)
![微信图片_20191029174605](https://user-images.githubusercontent.com/28742304/67811838-08111b80-fa74-11e9-9c2e-4a58fa4858d6.png)
![微信图片_20191029174612](https://user-images.githubusercontent.com/28742304/67811839-08111b80-fa74-11e9-8553-cb06fea5ae1b.png)
只有2位上班员工但是经理好像每人都做了3次payout的行动

**Comment by huangxuewu** [comment]
已经修复并更新
