### ISSUE TITLE
Mikado Middle Town -今晚修复礼物卡void问题 11/8/19

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#320]
- [x] 1.客人购买礼物卡时用信用卡付款，但是商家做错了多收了一份，要做void时无法成功界面
![微信图片编辑_20191108114409](https://user-images.githubusercontent.com/28742304/68495045-6f219380-021d-11ea-9e5f-f2c42878aa48.jpg)

**Comment by huangxuewu** [comment]
信用卡交易已经作废， 帐已过，版本已经更新。 s1 需要更新
