### ISSUE TITLE
Suishaya-需求

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#321]
- [x] 1.店里和akira 店一样，都在做餐给15%off活动 ，酒水除外来的，希望尽快修复

**Comment by huangxuewu** [comment]
当前版本有什么问题？

**Comment by qqqpos** [comment]
> 当前版本有什么问题？

会出现有些物品不打折
![微信图片编辑_20191119153707](https://user-images.githubusercontent.com/28742304/69184542-0ec70780-0ae3-11ea-8699-72ff39c7a3fe.jpg)

**Comment by qqqpos** [comment]
会出现有些物品不打折，在双份同一道菜上打折时前面会多出一个3的数字
![微信图片_20191119154108](
https://user-images.githubusercontent.com/28742304/69184561-1686ac00-0ae3-11ea-9d24-e0647902ae48.jpg
)
