### ISSUE TITLE
lucky Chen-礼物卡问题

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#322]
- [x] 1. 客人店里使用的礼物卡是19位数字，的现在购买礼物卡的回来使用礼物卡时，电脑刷过去时只能显示16位数字，不能完全显示出19位数字问题

**Comment by huangxuewu** [comment]
哪个界面？

**Comment by qqqpos** [comment]
在主界面查看礼物卡界面
![微信图片编辑_20191119153707](https://user-images.githubusercontent.com/28742304/69184273-8c3e4800-0ae2-11ea-9e35-49b645b1fdf7.jpg)

**Comment by qqqpos** [comment]
> 哪个界面？
在主界面买礼物卡画面，查看礼物卡时
![微信图片_20191119154108](https://user-images.githubusercontent.com/28742304/69184715-62395580-0ae3-11ea-97e9-1baaad235ff2.jpg)

**Comment by qqqpos** [comment]
在主界面买礼物卡画面，查看礼物卡时
![Inked微信图片编辑_20191119153707_LI](
https://user-images.githubusercontent.com/28742304/69184852-a9274b00-0ae3-11ea-816c-999ac18527a3.jpg
)

**Comment by huangxuewu** [comment]
新版本中已经添加了对19位卡号的支持
