### ISSUE TITLE
Little Tokyo

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#34]
- [x] 每次企台要Clock Out的时候, 想让企台必须报告现金小费, 这样等到月底结账的时候 就可以给企台结算小费
- [ ] ~~堂吃点餐界面想要把Done那个按钮一分为二, 变成一个是done:可以发送餐到厨房但是不会打印receipt. 另外一个变成receipt: 只打印receipt,不发送到厨房.~~
- [ ] ~~不想要在Hibachi桌子点餐的时候再多点一次中间的那个桌子~~
- [x] 希望能做企台私人的Cash In和 Cash Out, 另外一家店Zeafood Boil也需要这个功能, 因为企台打私产, 打完clock out后需要立即做cashier out然后把一天内所有的订单钱和小费都交到cashier的钱箱里面去. 然后月底才结算该企台的工资
- [ ] ~~因为企台和铁板师傅需要分小费, 所以等到月底的时候, 老板希望企台的工资里面能自动扣除掉需要分给铁板师傅的小费~~
- [x] 想设置一个权限, 企台下单以后的餐不可以再进行任何更改 包括加要求也不可以, 然后会请求输入manager里面, 只有manager的权限才可以进行更改
- [x] 分单后希望子单可以在history里面直接显示出来,比如说分单的时候8号单, 历史中会显示8-1,8-2,8-3. 这样的话可以对分单后的子单来进行独立操作的时候会更容易一些, 也可以更加一目了然分出来的单

**Comment by qqqpos** [comment]
- [ ] 希望能做企台私人的Cash In和 Cash Out, 另外一家店Zeafood Boil也需要这个功能, 因为企台打私产, 打完clock out后需要立即做cashier out然后把一天内所有的订单钱和小费都交到cashier的钱箱里面去. 然后月底才结算该企台的工资

**Comment by qqqpos** [comment]
- [ ] 因为企台和铁板师傅需要分小费, 所以等到月底的时候, 老板希望企台的工资里面能自动扣除掉需要分给铁板师傅的小费

**Comment by qqqpos** [comment]
- [ ] 想设置一个权限, 企台下单以后的东西不可以再进行更改, 除非用了manager的权限

**Comment by qqqpos** [comment]
分单后希望子单可以在history里面直接显示出来,比如说分单的时候8号单, 历史中会显示8-1,8-2,8-3. 这样的话可以对分单后的子单来进行独立操作的时候会更容易一些, 也可以更加一目了然分出来的单

**Comment by huangxuewu** [comment]
大多数功能都有,查看分单功能计划会加入

**Comment by huangxuewu** [comment]
已经完成
