### ISSUE TITLE
9.6 堂吃点餐/打印问题

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#37]
- [x] 外等或者送餐的单子改成堂吃后, 回到堂吃页面找这个单子的时候桌子会失效.

- [x] 堂吃单在按带走前点完餐后,再按带走,继续点餐,点完后按打印. 带走列表里的东西会正常打印出来 但是原先堂吃单后添加的东西会被hold在那

**Comment by huangxuewu** [comment]
对了 就是后面这个BUG
