### ISSUE TITLE
付款

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#38]
#38 订单再付款后店家点击历史中日期查看其他天的营业额时  突然客人有说换另外一个人来付款要求把刚刚订单移除付款  这时店家再把日期改回当天日期 点击刚刚订单移除付款  再移除后订单的颜色还是处于付款的形式 变得无法再付款需要退出主页面后 要再次点击历史进去才会出现刚刚订单是没付款的状态才能进行第2次付款选项

**Comment by huangxuewu** [comment]
已经修复
