### ISSUE TITLE
堂吃--分单 和 完整单  打印问题

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#40]
堂吃--分单 和 完整单 付款 后 点击pint 打印机没有任何反应 这个是不管再堂吃页面付款还是再历史页面付款都不会打印——>
![_20180828111635](https://user-images.githubusercontent.com/28742304/44732683-dd17ea00-aab3-11e8-8faf-4328138c43fa.jpg)
这个问题只有再堂吃出现   外卖和来取 没有问题

**Comment by huangxuewu** [comment]
cashier 打印订单 里面的 DINEIN 选单被取消.
