### ISSUE TITLE
外卖订单被合并到堂吃后问题

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#41]
?两张单从外卖合并到堂吃去后出现问题——>
1-->进入合并但里面 第一个问题是外卖那张单应该是被合并掉应该处于红色状态  。。现在显示的是正常单子蓝色显示来的 ---->
2. 然后进入堂吃的订单时是无法把原来的餐进行做任何修改来的--->
但是进入外卖的单子里面就可以进行修改原先外卖点的餐来的 ---->
3.再外卖的单子原先地方删除一道菜后 点击保存 出来后再点击进去合并单里面后--->
 这次的页面就显示被合的外卖单---->
出现外等的单已经变成红色状态了----->
但是再堂吃那边单子上就不会显示出刚刚再外卖单子里删除的餐---->
接着就是这个订单改动后 就再也无法开启这张合并单子做任何事情了只限制再历史那边页面----> 
再堂吃页面地方可以再继续加餐---> 
就是无法删除原先点的餐了----->
然后再进行付款时如果点到分单付款选项里的话是无法付款来的  ---->
要关闭这个分单付款画面只能点击保存

**Comment by huangxuewu** [comment]
无法重现发现相关的问题, 请重启服务器
