### ISSUE TITLE
客人要求：FUJIAN Grand China Buffet_Server

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#42]
1.这家店客人希望把店名字  字体变小和变细  变得和地址一样  然后还希望再订单上面的单号不要显示出来

2.然后buffet模式下 付款现金无法使用 信用卡可以  但是有一点问题就是信用卡付完后  无法便回buffet模式快速点餐页面
![_20180828145720](https://user-images.githubusercontent.com/28742304/44744270-c1700c00-aad2-11e8-9ad6-b5d8eb38fbe0.jpg)
3.客人要求说 再Category 那边有没有办法区分开 比如再lunch 时段时一直保持再那个页面再lunch Category  那边  到晚餐时候 category就一直保持再dinner页面   然后Saturday 时候category就保持再那边
Sunday 时候也是那样   想要这个东西根据时间 和日期自行调换

**Comment by huangxuewu** [comment]
经检查,BUFFET 模式可以使用现金付款

**Comment by huangxuewu** [comment]
付款之后无法返回buffet模式快速点餐 已经修复

**Comment by huangxuewu** [comment]
在BUFFET 模式下 重置菜单并不会重置 所选的category. 因此 第三个需求暂时不考虑
