### ISSUE TITLE
Asian King_奇怪问题

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#45]
![_20180828160202](https://user-images.githubusercontent.com/28742304/44747794-02205300-aadc-11e8-9532-e3be3256305b.jpg)

他这张单很奇怪 他变得Any two roll会在kitchen 打印出来了 我试着再我们电脑上面点相同的订单但都不会出现这个问题 你今晚有事查下 他的database我拉回来了再我电脑上

**Comment by huangxuewu** [comment]
这个是用键盘输入引起的一个BUG 新版本已经修复
