### ISSUE TITLE
超级紧急--礼物卡需求

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#52]
1.客人店里使用的是礼物纸 不是礼物卡
2.需要手动输入礼物纸上的数字后在激活
3.激活后 客人把自己电话号码输入进去
4.店家可以通过卡号 或电话号码查找出 客人的卡上资料
5.进行付款

**Comment by huangxuewu** [comment]
已完成, 手动输入卡号可以参考一下步骤

![500b393f4fbe4a56a5cb10c3f5aa7b1](https://user-images.githubusercontent.com/6463693/46680063-3b0d1680-cbb6-11e8-8f0b-e8b644dc16c3.png)

![c0d1b99041923eecee7c2caca1ebe02](https://user-images.githubusercontent.com/6463693/46680070-3d6f7080-cbb6-11e8-904c-2165bd6f5797.png)

![124d99d23bdc0f6c56813406122b858](https://user-images.githubusercontent.com/6463693/46680080-43fde800-cbb6-11e8-822a-a9e213dfab1b.png)

![cfffe819ee7f4d887ac7ae03b430697](https://user-images.githubusercontent.com/6463693/46680096-4b24f600-cbb6-11e8-94f1-5d5c6dc908d6.png)
