### ISSUE TITLE
付款增加一个house account

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#55]
- [ ] 1.付款里面增加一个house account使用
- [ ] 2.店家送给客人的礼物卡可以通过house account付掉
- [ ] 3.使用house account付款的钱不会计算在当天营业额的总数里面
- [ ] 4.报表上面会显示使用过house account的人名 和日期金额
- [ ] 5.关于house account 还有一点如果碰上像东田那边的情况一样这样怎么处理 --东田那边是客人先赊账然后月底或者月初又或者是几个星期结算一次 那它当他吃的餐价格是如何体现出来处理

**Comment by huangxuewu** [comment]
暂时hold住
