### ISSUE TITLE
关于折扣

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#56]
- [x] 1.折扣完整订单
- [x] 2.完整订单上面能否设置成酒水部分不打折
- [x] 3.happy hour的酒水也不在打折范围之内
- [x] 4.客人也可以根据他们自己的喜好进行设置那里不打折的情况

**Comment by huangxuewu** [comment]
关于第一点 折扣完整订单 我们目前只有 按SUBTOTAL 或者 TOTAL 折扣, 类似 tip 和delivery fee 和 gratuity 是单独的 ,并不能折扣掉, 选项在设定->店面->付款->税率->折扣前征税

**Comment by huangxuewu** [comment]
关于第二点 只能使用coupon来实现

**Comment by huangxuewu** [comment]
第三点也是如此

**Comment by huangxuewu** [comment]
第四点也是

**Comment by huangxuewu** [comment]
功能已经全部完成
