### ISSUE TITLE
juice seafood

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#68]
lunch 跟 dinner report的问题
现在客人5点前下单，过了5点后付款和加小费。report里面会把他当成5点后（dinner）的订单

**Comment by huangxuewu** [comment]
0.9.80 可以去付款 高级设置里面 开启以下功能即可

![c1939b5d0024f51e52de48c8041bc49](https://user-images.githubusercontent.com/6463693/46028464-a6d38780-c0be-11e8-997e-87c7d33b9c6a.png)
