### ISSUE TITLE
Juicy Seafood --打印字体歪

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#73]
- [ ] 1.Juicy Seafood 的fryer打印机字体出现歪
- [ ] 2. 重启c-lodop后就正常 怀疑是这次安装的是32位版本导致
![_20180922132618](https://user-images.githubusercontent.com/28742304/45919917-25d08200-be6b-11e8-8f8b-5f7b502165e2.jpg)

**Comment by huangxuewu** [comment]
这个是ie 渲染引擎失效, 重启电脑
