### ISSUE TITLE
关于要求那边使用keyboard

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#74]
- [ ] 1.列如输入时时这个样子来的
![_20180925102644](https://user-images.githubusercontent.com/28742304/46021184-0c6b4800-c0ae-11e8-9132-09c20fa35b35.jpg)
- [ ] 2.中间那个DuckSauce字连再一起了要想再中间加入一个空格把这两个字分开
![_20180925102713](https://user-images.githubusercontent.com/28742304/46021232-302e8e00-c0ae-11e8-9607-b706813b097b.jpg)
- [ ] 3.点完空格后全部字都变得不见了 变得又要从新输入一次麻烦进行优化
![_20180925102743](https://user-images.githubusercontent.com/28742304/46021278-4f2d2000-c0ae-11e8-8832-45b8690bdcb5.jpg)

**Comment by huangxuewu** [comment]
0.9.80 后修复,不过如果在选择了自动填写的 情况之下
![1301561bc86f7fe991e070569ae4a6a](https://user-images.githubusercontent.com/6463693/46028795-7e985880-c0bf-11e8-9f78-1521c182e61b.png)

也会出现重置的问题
