### ISSUE TITLE
Enso 修复物品增加物品有价格

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#75]
- [x] 1.关于正餐或酒类再正餐价格下面增加物品而增加物品是有价格如图
![_20180925103315](https://user-images.githubusercontent.com/28742304/46021453-b64ad480-c0ae-11e8-9f09-c49f362de0ff.jpg)
- [x] 2.客人要是需要两杯的话只有正常价格会增加双份 而正常增加物品不会收取双份金钱如图
![_20180925103323](https://user-images.githubusercontent.com/28742304/46021526-e6927300-c0ae-11e8-811a-2759d1b641de.jpg)
- [x] 3.要显示真确的价格只能把相同的物品分开输入2次才可以 如图
![_20180925103329](https://user-images.githubusercontent.com/28742304/46021594-09bd2280-c0af-11e8-868e-3e46bc69c9a2.jpg)

**Comment by huangxuewu** [comment]
在新版本中可以去 物品 设置里面 打开
![48d9057fa3d69c21ac50c3c92e4b963](https://user-images.githubusercontent.com/6463693/46041337-85839300-c0e0-11e8-9ea8-df02b2ddefeb.png)
