### ISSUE TITLE
ShanghaiGourmet 要求

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#76]
- [ ] 1. 客人想要再收据电话号码下面加入自己的网站来显示出来

**Comment by huangxuewu** [comment]
0.9.8 已经加入 在店面设置里面
![b312606658ac7eb2f5c89d2f4a7423b](https://user-images.githubusercontent.com/6463693/46029336-1d718480-c0c1-11e8-8693-4fc0843c3aee.png)
