### ISSUE TITLE
[Fuh Wah] 一键付款要求

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#78]
- [ ] 1.这家店是全现金付款来的老板希望可以增加一个一键付款全部订单 不想一张一张单付款掉

**Comment by huangxuewu** [comment]
在最新版本中 使用开发者账号 或者 店主的账号登录进历史里面 点击所有订单可以看到

![fe16e4be7c21bb4a0ff37ad71774a90](https://user-images.githubusercontent.com/6463693/46261759-3e254a00-c4c6-11e8-9478-a81c2ac18f3c.png)
