### ISSUE TITLE
New Storming Crab --要求

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#79]
- [ ] 1.鸡尾酒那边比如可以点了这样一杯酒如图
![_20180928133315](https://user-images.githubusercontent.com/28742304/46224068-3aa58d80-c323-11e8-8976-7865ec52d7c2.jpg)
- [ ] 2.其实客人是点了两杯相同的酒在后台也把这个地方开启如图
![_20180928133617](https://user-images.githubusercontent.com/28742304/46224196-996b0700-c323-11e8-83f2-760094f7bfbd.jpg)
- [ ] 3.也不会改变把下方这个有价钱的字前面增加数字上面只有在主的那杯酒会变得显示2这个数字 如图
![_20180928133255](https://user-images.githubusercontent.com/28742304/46224267-d1724a00-c323-11e8-956d-f020d8d17b4b.jpg)
- [ ] 4. 客人想要变2杯是下面的跟着搭配的酒材料数字也变成双份 如图这样效果
![_20180928134048](https://user-images.githubusercontent.com/28742304/46224356-21511100-c324-11e8-905e-e3321b043b53.jpg)

**Comment by huangxuewu** [comment]
新版本已经是这样的了
