### ISSUE TITLE
Enso Request

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#82]
- [x] 1.希望能在充值礼物卡的时候可以免单， 这样客人以前充的礼物卡的数据可以搬到我们软件来使用。
- [x] 2.客人想把之前卖出去的礼物卡通过后台把它添加进数据库里面去
- [ ] ~~3.相同也是再vip卡积分卡也是可以再后台地方填写之前卖出去的客人资料~~
- [ ] ~~4.只有持有vip卡的客人才可以享受有积分这种待遇  没有卡的客人就没有这样的权力~~
- [x] 5. 启台个人报表增加有TIP Out这个项目 还有启台签名这行字如图显示这样
![_20181001172325](https://user-images.githubusercontent.com/28742304/46316638-b8c19880-c59e-11e8-812f-dc1ea9e4c1b4.jpg)
- [x] 6.Tip Out 这行启台自己填写
- [x] 7.Hibachi合单到Hibachi订单去时再合进去的订单里面看不到被合的订单餐再里面
- [x] 8.被合的Hibachi订单无法用经理以下包括经理权限都无法恢复被合订单
- [x] 9.viod报表里面增加单一 一道菜被viod掉也要显示出来  显示出来的效果要求订单号码 被viod掉的菜的名字 和处理viod这件事的人名

**Comment by huangxuewu** [comment]
关于第8条 , 这个权限仅放给店主 或者开发者账户
