### ISSUE TITLE
[堂吃] 针对Food Court付款模式

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#87]
- [ ] 1.再Food Court里面无需使用桌面桌位的模式下增加付款按键再里面 相同外卖那边点餐页面

**Comment by huangxuewu** [comment]
![4428c0ed2a965a24b30b005fdaba31b](https://user-images.githubusercontent.com/6463693/46987621-feb04d80-d0c2-11e8-9064-9bfdbafca8eb.png)

关闭座位选项之后

![cf5b373e71a9b48b0eae0d5df7efacd](https://user-images.githubusercontent.com/6463693/46987632-0f60c380-d0c3-11e8-920d-d391bf1aba4d.png)

付款按钮就会在下单界面出现

**Comment by qqqpos** [comment]
这个版本再直接点单完按付款后选择支付现金 信用卡后 点击打印只会打印餐再厨房里面显示出来  无法打印出来收据给客人

**Comment by huangxuewu** [comment]
![fa2a4f34820d09442a9aaa448cffe18](https://user-images.githubusercontent.com/6463693/47167642-f0ce1880-d2cc-11e8-8a58-d71145fe229f.png)

开启此选项
