### ISSUE TITLE
Fujian Buffet 需求

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#88]
- [ ] 0. 这家店的需求可以暂时Hold一段时间后处理等老板需求全部说完后再处理
- [ ] 1.和老板说了我们会为它订做一个它需求的软件样式给它也和它说这个版本将不会再进行任何更新软件事件
- [ ] 2.老板需求---点餐页面的Menu Category的蓝色底色和Menu Item底色相互兑换
- [ ] 3. 再软件左上方的订单号码也无需显示出来

**Comment by huangxuewu** [comment]
目前没有计划实现上述要求
