### ISSUE TITLE
18-8 sushi 需求

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#89]
- [ ] 1.  18-8sushi需求要打印出每个月的堂吃/外卖/来取/送餐/网络订单的每个总金额报表出来查看

**Comment by huangxuewu** [comment]
目前不支持网络订单总数查看和打印

![ff8aa17944cbef907241728a0d9bf7d](https://user-images.githubusercontent.com/6463693/46698795-fc8f5000-cbe5-11e8-9129-e52699c428c1.png)
