### ISSUE TITLE
- [ ] 3. 如果只有hibachitable客人达到店家规定的人数后默认收取服务费的话该如何处理

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#94]
_Originally posted by @qqqpos in https://github.com/huangxuewu/entree/issue_comments#issuecomment-431406222_

**Comment by huangxuewu** [comment]
HIBACHI 的客人是按照座位来计算的. 只需要 选中 规定数量的座位就会自动计算服务费
