### ISSUE TITLE
今晚 Fuji Grill 更新

### ISSUE THREAD

**Issue by qqqpos** [huangxuewu/entree#99]
- [x] 1.再第三方付款地方增加新的botton名字就Chownow
- [x] 2.再堂吃桌位地方区域可以进行拉动调整位子
- [ ] 3.hibachi桌位上点厨房餐时需要再厨房打印机打印出来  但是hibachi的餐不需要

**Comment by qqqpos** [comment]
在会hibachi上面点apptizer，厨房没有单子。打到酒吧的单子，只显示新的订单，不需要其他东西显示出来

**Comment by huangxuewu** [comment]
某些时候 重启软件即可
